MP_ACCESS_TOKEN = "APP_USR-8017809787623270-060217-4db7a25e852e867b8393b2a91943ac89-640632266"
CBU_ALIAS       = "TU_ALIAS_CBU_AQUI"
BASE_URL        = "https://almapaid.streamlit.app/"  # o la URL pública de tu servidor
